# Generated by Django 3.2.9 on 2021-11-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='has_seen',
            field=models.BooleanField(default=False),
        ),
    ]
