# Generated by Django 3.2.9 on 2021-11-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_has_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
